version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: marketgarden
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  influxdb:
    image: influxdb:latest
    container_name: influxdb1
    networks:
      - influxdb-grafana
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=mypassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
    volumes:
      - influxdb:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana1
    networks:
      - influxdb-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  influxdb-grafana:

volumes:
  influxdb:
  grafana-storage:
  postgres_data: